echo '------------------------------------------------------------------------'
echo '  ______                ____            _     '
echo ' |  ____|              |  _ \          | |    '
echo ' | |__   __ _ ___ _   _| |_) | __ _ ___| |__  '
echo ' |  __| / _` / __| | | |  _ < / _` / __| |_ \ '
echo ' | |___| (_| \__ \ |_| | |_) | (_| \__ \ | | |'
echo ' |______\__,_|___/\__, |____/ \__,_|___/_| |_|'
echo '                   __/ |                      '
echo '                  |___/                       '
echo '------------------------------------------------------------------------'
echo 'Dados do sistema:'
uname -a
echo '------------------------------------------------------------------------'

echo 'Atualizando os pacotes do sistema:'
apt-get update
echo '------------------------------------------------------------------------'

echo 'Atualizando o sistema:'
apt-get upgrade -y
echo '------------------------------------------------------------------------'

echo 'Limpando o sistema de arquivos temporários e desnecessários'
echo '------------------------------------------------------------------------'
echo 'Espaço que os arquivos de pacotes .deb estavam ocupando:'
du -sh /var/cache/apt/archives
echo '------------------------------------------------------------------------'
## AUTOREMOVE - remover pacotes que foram instalados automaticamente para satisfazer dependências de outros pacotes e que já não são mais necessários.

apt-get autoremove -y
echo '------------------------------------------------------------------------'
## AUTOCLEAN - Limpa o seu repositório local — removendo os arquivos de pacotes (.deb) que não podem mais ser baixados (versões antigas) e são completamente inúteis e obsoletos.

apt-get autoclean -y
echo '------------------------------------------------------------------------'
## CLEAN -  Limpando e removendo todos os arquivos .deb (pacotes) contidos nos diretórios — exceto o lock file.

apt-get clean -y
echo '------------------------------------------------------------------------'
echo 'Limpeza realizada com sucesso!'
echo '------------------------------------------------------------------------'
echo 'Espaço que os arquivos de pacotes .deb estão ocupando:'
du -sh /var/cache/apt/archives
echo '------------------------------------------------------------------------'
